name: Security Audit

on:
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'deny.toml'
      - '.github/workflows/audit.yml'
  push:
    branches:
      - master
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'deny.toml'
      - '.github/workflows/audit.yml'
  schedule:
    # Run at 00:00 UTC every Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cargo-deny:
    name: cargo-deny
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@v2